name: tracker_sandbox
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pip
  - pip:
      - gymnasium[mujoco]
      - stable-baselines3[extra]
      - jsonargparse
      - tensorboard
      - colorlog
      - mlflow
      - flatten-dict
      - dvc
      - dvc_s3
      - optuna
