policy_mlp:
  name: node_graph
  params:
    nodes:
      - name: linear
        params:
          out_features: 64
      - name: lif
        params: {}
      - name: linear
        params:
          out_features: 2
value_mlp:
  name: node_graph
  params:
    nodes:
      - name: linear
        params:
          out_features: 64
      - name: lif
        params: {}
      - name: linear
        params:
          out_features: 1
