policy_mlp:
  name: node_graph
  params:
    nodes:
      - name: linear
        params:
          out_features: 64
      - name: lif
      - name: linear
        params:
          out_features: 128
      - name: lif
      - name: linear
        params:
          out_features: 64
      - name: li
      - name: linear
        params:
          out_features: 2
