nodes:
  - name: linear
    params:
      out_features: 64
  - name: torch_activation
    params:
      activation: relu
  - name: linear
    params:
      out_features: 128
  - name: torch_activation
    params:
      activation: relu
  - name: linear
    params:
      out_features: 64
  - name: torch_activation
    params:
      activation: relu
  - name: linear
    params:
      out_features: 2
