defaults:
  - base_config
  - agent: null
  - env: null
  - optuna: null
  - runner: null
  - trainer: null
  - experiment: reinforce_cartpole_snn
  - override hydra/job_logging: colorlog
  - _self_

hydra:
  run:
    dir: runs/${runner.experiment_name}/${env.params.id}/${now:%Y-%m-%d_%H-%M-%S}_${agent.name}
  sweep:
    dir: runs/${runner.experiment_name}/${env.params.id}/${now:%Y-%m-%d_%H-%M-%S}_${agent.name}
    subdir: ${hydra.job.num}
