defaults:
  - base_config
  - agent: ppo
  - env: pendulum_v1
  - optuna: base
  - models: mlp
  - runner: base
  - trainer: base
  - override hydra/job_logging: colorlog
  - _self_

hydra:
  run:
    dir: runs/${runner.experiment_name}/${env.id}/${now:%Y-%m-%d_%H-%M-%S}_${agent.name}
  sweep:
    dir: runs/${runner.experiment_name}/${env.id}/${now:%Y-%m-%d_%H-%M-%S}_${agent.name}
    subdir: ${hydra.job.num}
