defaults:
  - /models@params.policy: reinforce_mlp
  - _self_

name: reinforce
params:
  device: cuda
  rollouts: 64
  learning_rate: 1e-3
  learning_rate_scheduler: null
  observation_preprocessor: skrl.resources.preprocessors.torch.RunningStandardScaler
  experiment:
    write_interval: 2000
