rl_params:
  mode: train # train, optimize, evaluate
  seed: 42
  experiment_name: test
  checkpoint_path: null
  device: cuda

  env:
    id: Ant-v5
    n_envs: 16
    render_mode: human
    normalization:
      enable: True
      norm_obs: True
      norm_reward: True
      params:
        clip_obs: 10


  algorithm:
    name: ppo
    params:
      learning_rate: 3e-4
      n_steps: 2048
      batch_size: 256
      n_epochs: 4
      ent_coef: 0.01

  policy:
    name: mlp
    params:
      net_arch: [256, 256]

  optuna:
    n_trials: 50
    parameters:
      - parameter: algorithm.learning_rate
      - parameter: policy.hidden_size

  training:
    total_timesteps: 8000000
    n_eval_episodes: 20

  logging:
    folder: logs